version: '3'
services:
  scalextrics-docker:
    image: scalextrics-docker:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 ./main.py --host='0.0.0.0' --debug
    ports:
      - 5000:5000
    stdin_open: true
    tty: true
